// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	sql0 "database/sql"

	"github.com/diegodesousas/go-devkit/pkg/database/sql"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection struct {
	mock.Mock
}

type MockConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnection) EXPECT() *MockConnection_Expecter {
	return &MockConnection_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockConnection
func (_mock *MockConnection) Begin(ctx context.Context) (sql.Transaction, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 sql.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (sql.Transaction, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) sql.Transaction); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockConnection_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnection_Expecter) Begin(ctx any) *MockConnection_Begin_Call {
	return &MockConnection_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockConnection_Begin_Call) Run(run func(ctx context.Context)) *MockConnection_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnection_Begin_Call) Return(transaction sql.Transaction, err error) *MockConnection_Begin_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockConnection_Begin_Call) RunAndReturn(run func(ctx context.Context) (sql.Transaction, error)) *MockConnection_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockConnection
func (_mock *MockConnection) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Close() *MockConnection_Close_Call {
	return &MockConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConnection_Close_Call) Run(run func()) *MockConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Close_Call) Return(err error) *MockConnection_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_Close_Call) RunAndReturn(run func() error) *MockConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockConnection
func (_mock *MockConnection) Exec(ctx context.Context, query string, args ...any) (sql0.Result, error) {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql0.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sql0.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sql0.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql0.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockConnection_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockConnection_Expecter) Exec(ctx any, query any, args ...any) *MockConnection_Exec_Call {
	return &MockConnection_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, query}, args...)...)}
}

func (_c *MockConnection_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockConnection_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockConnection_Exec_Call) Return(result sql0.Result, err error) *MockConnection_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockConnection_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sql0.Result, error)) *MockConnection_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockConnection
func (_mock *MockConnection) Get(ctx context.Context, dest any, query string, args ...any) error {
	var _ca []any
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConnection_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *MockConnection_Expecter) Get(ctx any, dest any, query any, args ...any) *MockConnection_Get_Call {
	return &MockConnection_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, dest, query}, args...)...)}
}

func (_c *MockConnection_Get_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *MockConnection_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		variadicArgs := make([]any, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockConnection_Get_Call) Return(err error) *MockConnection_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_Get_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *MockConnection_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockConnection
func (_mock *MockConnection) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockConnection_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Ping() *MockConnection_Ping_Call {
	return &MockConnection_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockConnection_Ping_Call) Run(run func()) *MockConnection_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Ping_Call) Return(err error) *MockConnection_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_Ping_Call) RunAndReturn(run func() error) *MockConnection_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockConnection
func (_mock *MockConnection) Select(ctx context.Context, dest any, query string, args ...any) error {
	var _ca []any
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockConnection_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *MockConnection_Expecter) Select(ctx any, dest any, query any, args ...any) *MockConnection_Select_Call {
	return &MockConnection_Select_Call{Call: _e.mock.On("Select",
		append([]any{ctx, dest, query}, args...)...)}
}

func (_c *MockConnection_Select_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *MockConnection_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		variadicArgs := make([]any, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockConnection_Select_Call) Return(err error) *MockConnection_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_Select_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *MockConnection_Select_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionContext provides a mock function for the type MockConnection
func (_mock *MockConnection) TransactionContext(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for TransactionContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_TransactionContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionContext'
type MockConnection_TransactionContext_Call struct {
	*mock.Call
}

// TransactionContext is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockConnection_Expecter) TransactionContext(ctx any, fn any) *MockConnection_TransactionContext_Call {
	return &MockConnection_TransactionContext_Call{Call: _e.mock.On("TransactionContext", ctx, fn)}
}

func (_c *MockConnection_TransactionContext_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockConnection_TransactionContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_TransactionContext_Call) Return(err error) *MockConnection_TransactionContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_TransactionContext_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockConnection_TransactionContext_Call {
	_c.Call.Return(run)
	return _c
}
