// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockErrorWriter creates a new instance of MockErrorWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockErrorWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockErrorWriter is an autogenerated mock type for the ErrorWriter type
type MockErrorWriter struct {
	mock.Mock
}

type MockErrorWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorWriter) EXPECT() *MockErrorWriter_Expecter {
	return &MockErrorWriter_Expecter{mock: &_m.Mock}
}

// Match provides a mock function for the type MockErrorWriter
func (_mock *MockErrorWriter) Match(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockErrorWriter_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockErrorWriter_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - err error
func (_e *MockErrorWriter_Expecter) Match(err any) *MockErrorWriter_Match_Call {
	return &MockErrorWriter_Match_Call{Call: _e.mock.On("Match", err)}
}

func (_c *MockErrorWriter_Match_Call) Run(run func(err error)) *MockErrorWriter_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockErrorWriter_Match_Call) Return(b bool) *MockErrorWriter_Match_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockErrorWriter_Match_Call) RunAndReturn(run func(err error) bool) *MockErrorWriter_Match_Call {
	_c.Call.Return(run)
	return _c
}

// MustLog provides a mock function for the type MockErrorWriter
func (_mock *MockErrorWriter) MustLog() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MustLog")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockErrorWriter_MustLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustLog'
type MockErrorWriter_MustLog_Call struct {
	*mock.Call
}

// MustLog is a helper method to define mock.On call
func (_e *MockErrorWriter_Expecter) MustLog() *MockErrorWriter_MustLog_Call {
	return &MockErrorWriter_MustLog_Call{Call: _e.mock.On("MustLog")}
}

func (_c *MockErrorWriter_MustLog_Call) Run(run func()) *MockErrorWriter_MustLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorWriter_MustLog_Call) Return(b bool) *MockErrorWriter_MustLog_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockErrorWriter_MustLog_Call) RunAndReturn(run func() bool) *MockErrorWriter_MustLog_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockErrorWriter
func (_mock *MockErrorWriter) Write(w http.ResponseWriter, err error) error {
	ret := _mock.Called(w, err)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, error) error); ok {
		r0 = returnFunc(w, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockErrorWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockErrorWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - err error
func (_e *MockErrorWriter_Expecter) Write(w any, err any) *MockErrorWriter_Write_Call {
	return &MockErrorWriter_Write_Call{Call: _e.mock.On("Write", w, err)}
}

func (_c *MockErrorWriter_Write_Call) Run(run func(w http.ResponseWriter, err error)) *MockErrorWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockErrorWriter_Write_Call) Return(err1 error) *MockErrorWriter_Write_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockErrorWriter_Write_Call) RunAndReturn(run func(w http.ResponseWriter, err error) error) *MockErrorWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
