// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/diegodesousas/greeter/internal/domain/greeting"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGreetingRepository creates a new instance of MockGreetingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGreetingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGreetingRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGreetingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGreetingRepository is an autogenerated mock type for the Repository type
type MockGreetingRepository struct {
	mock.Mock
}

type MockGreetingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGreetingRepository) EXPECT() *MockGreetingRepository_Expecter {
	return &MockGreetingRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockGreetingRepository
func (_mock *MockGreetingRepository) List(ctx context.Context, page int, perPage int) ([]greeting.Greeting, int, error) {
	ret := _mock.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []greeting.Greeting
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]greeting.Greeting, int, error)); ok {
		return returnFunc(ctx, page, perPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []greeting.Greeting); ok {
		r0 = returnFunc(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]greeting.Greeting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, page, perPage)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGreetingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGreetingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - perPage int
func (_e *MockGreetingRepository_Expecter) List(ctx any, page any, perPage any) *MockGreetingRepository_List_Call {
	return &MockGreetingRepository_List_Call{Call: _e.mock.On("List", ctx, page, perPage)}
}

func (_c *MockGreetingRepository_List_Call) Run(run func(ctx context.Context, page int, perPage int)) *MockGreetingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGreetingRepository_List_Call) Return(greetings []greeting.Greeting, n int, err error) *MockGreetingRepository_List_Call {
	_c.Call.Return(greetings, n, err)
	return _c
}

func (_c *MockGreetingRepository_List_Call) RunAndReturn(run func(ctx context.Context, page int, perPage int) ([]greeting.Greeting, int, error)) *MockGreetingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockGreetingRepository
func (_mock *MockGreetingRepository) Save(ctx context.Context, g greeting.Greeting) error {
	ret := _mock.Called(ctx, g)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, greeting.Greeting) error); ok {
		r0 = returnFunc(ctx, g)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGreetingRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockGreetingRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - g greeting.Greeting
func (_e *MockGreetingRepository_Expecter) Save(ctx any, g any) *MockGreetingRepository_Save_Call {
	return &MockGreetingRepository_Save_Call{Call: _e.mock.On("Save", ctx, g)}
}

func (_c *MockGreetingRepository_Save_Call) Run(run func(ctx context.Context, g greeting.Greeting)) *MockGreetingRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 greeting.Greeting
		if args[1] != nil {
			arg1 = args[1].(greeting.Greeting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGreetingRepository_Save_Call) Return(err error) *MockGreetingRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGreetingRepository_Save_Call) RunAndReturn(run func(ctx context.Context, g greeting.Greeting) error) *MockGreetingRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockGreetingRepository
func (_mock *MockGreetingRepository) Search(ctx context.Context, name string, page int, perPage int) ([]greeting.Greeting, int, error) {
	ret := _mock.Called(ctx, name, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []greeting.Greeting
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]greeting.Greeting, int, error)); ok {
		return returnFunc(ctx, name, page, perPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []greeting.Greeting); ok {
		r0 = returnFunc(ctx, name, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]greeting.Greeting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = returnFunc(ctx, name, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, name, page, perPage)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGreetingRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockGreetingRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - page int
//   - perPage int
func (_e *MockGreetingRepository_Expecter) Search(ctx any, name any, page any, perPage any) *MockGreetingRepository_Search_Call {
	return &MockGreetingRepository_Search_Call{Call: _e.mock.On("Search", ctx, name, page, perPage)}
}

func (_c *MockGreetingRepository_Search_Call) Run(run func(ctx context.Context, name string, page int, perPage int)) *MockGreetingRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGreetingRepository_Search_Call) Return(greetings []greeting.Greeting, n int, err error) *MockGreetingRepository_Search_Call {
	_c.Call.Return(greetings, n, err)
	return _c
}

func (_c *MockGreetingRepository_Search_Call) RunAndReturn(run func(ctx context.Context, name string, page int, perPage int) ([]greeting.Greeting, int, error)) *MockGreetingRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}
