// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/diegodesousas/greeter/internal/application/greet"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGreetUseCase creates a new instance of MockGreetUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGreetUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGreetUseCase {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGreetUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGreetUseCase is an autogenerated mock type for the UseCase type
type MockGreetUseCase struct {
	mock.Mock
}

type MockGreetUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGreetUseCase) EXPECT() *MockGreetUseCase_Expecter {
	return &MockGreetUseCase_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockGreetUseCase
func (_mock *MockGreetUseCase) Run(ctx context.Context, dto greet.DTO) (greet.GreetingDTO, error) {
	ret := _mock.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 greet.GreetingDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, greet.DTO) (greet.GreetingDTO, error)); ok {
		return returnFunc(ctx, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, greet.DTO) greet.GreetingDTO); ok {
		r0 = returnFunc(ctx, dto)
	} else {
		r0 = ret.Get(0).(greet.GreetingDTO)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, greet.DTO) error); ok {
		r1 = returnFunc(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGreetUseCase_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockGreetUseCase_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - dto greet.DTO
func (_e *MockGreetUseCase_Expecter) Run(ctx any, dto any) *MockGreetUseCase_Run_Call {
	return &MockGreetUseCase_Run_Call{Call: _e.mock.On("Run", ctx, dto)}
}

func (_c *MockGreetUseCase_Run_Call) Run(run func(ctx context.Context, dto greet.DTO)) *MockGreetUseCase_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 greet.DTO
		if args[1] != nil {
			arg1 = args[1].(greet.DTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGreetUseCase_Run_Call) Return(greetingDTO greet.GreetingDTO, err error) *MockGreetUseCase_Run_Call {
	_c.Call.Return(greetingDTO, err)
	return _c
}

func (_c *MockGreetUseCase_Run_Call) RunAndReturn(run func(ctx context.Context, dto greet.DTO) (greet.GreetingDTO, error)) *MockGreetUseCase_Run_Call {
	_c.Call.Return(run)
	return _c
}
