// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/diegodesousas/greeter/internal/application/search_greetings"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchGreetingsUseCase creates a new instance of MockSearchGreetingsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchGreetingsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchGreetingsUseCase {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSearchGreetingsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSearchGreetingsUseCase is an autogenerated mock type for the UseCase type
type MockSearchGreetingsUseCase struct {
	mock.Mock
}

type MockSearchGreetingsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchGreetingsUseCase) EXPECT() *MockSearchGreetingsUseCase_Expecter {
	return &MockSearchGreetingsUseCase_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSearchGreetingsUseCase
func (_mock *MockSearchGreetingsUseCase) Run(ctx context.Context, dto search_greetings.DTO) (search_greetings.Output, error) {
	ret := _mock.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 search_greetings.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, search_greetings.DTO) (search_greetings.Output, error)); ok {
		return returnFunc(ctx, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, search_greetings.DTO) search_greetings.Output); ok {
		r0 = returnFunc(ctx, dto)
	} else {
		r0 = ret.Get(0).(search_greetings.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, search_greetings.DTO) error); ok {
		r1 = returnFunc(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchGreetingsUseCase_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSearchGreetingsUseCase_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - dto search_greetings.DTO
func (_e *MockSearchGreetingsUseCase_Expecter) Run(ctx any, dto any) *MockSearchGreetingsUseCase_Run_Call {
	return &MockSearchGreetingsUseCase_Run_Call{Call: _e.mock.On("Run", ctx, dto)}
}

func (_c *MockSearchGreetingsUseCase_Run_Call) Run(run func(ctx context.Context, dto search_greetings.DTO)) *MockSearchGreetingsUseCase_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 search_greetings.DTO
		if args[1] != nil {
			arg1 = args[1].(search_greetings.DTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearchGreetingsUseCase_Run_Call) Return(output search_greetings.Output, err error) *MockSearchGreetingsUseCase_Run_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockSearchGreetingsUseCase_Run_Call) RunAndReturn(run func(ctx context.Context, dto search_greetings.DTO) (search_greetings.Output, error)) *MockSearchGreetingsUseCase_Run_Call {
	_c.Call.Return(run)
	return _c
}
